[package]
name = "transaction"
version = "0.1.0"
authors = ["Bartłomiej Kuras <hash.deb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
csv = "1"
log = "0.4"
pretty_env_logger = "0.4"
